version: '3'

services:
  site:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
    container_name: site
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./dockerfiles/nginx/default.conf:/etc/nginx/default.conf